# Generated by Django 6.1.1 on 2026-10-05 11:53

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('providers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(choices=[('USD', 'US dollar'), ('EUR', 'Euro'), ('GBP', 'British pound')], max_length=3, unique=True, verbose_name='currency')),
                ('inr_per_unit', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='rupees per unit')),
                ('rate_date', models.DateField(verbose_name='rate date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'exchange rate',
                'verbose_name_plural': 'exchange rates',
                'ordering': ['currency'],
            },
        ),
        migrations.CreateModel(
            name='TreatmentPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('is_published', models.BooleanField(default=False, verbose_name='published')),
                ('price_min_inr', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='starting price (₹)')),
                ('price_max_inr', models.PositiveIntegerField(blank=True, help_text='Leave blank if the hospital quoted a single price.', null=True, verbose_name='upper price (₹)')),
                ('inclusions', models.TextField(blank=True, help_text='One item per line. Example: 5 nights in a private room.', verbose_name='included')),
                ('exclusions', models.TextField(blank=True, help_text='One item per line. Example: Implant upgrades.', verbose_name='not included')),
                ('price_updated_on', models.DateField(default=django.utils.timezone.localdate, help_text='When the hospital last confirmed this price.', verbose_name='price confirmed on')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='packages', to='providers.hospital', verbose_name='hospital')),
                ('treatment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='packages', to='catalog.treatment', verbose_name='treatment')),
            ],
            options={
                'verbose_name': 'treatment package',
                'verbose_name_plural': 'treatment packages',
                'ordering': ['price_min_inr'],
                'constraints': [models.UniqueConstraint(fields=('treatment', 'hospital'), name='pricing_package_unique_treatment_hospital', violation_error_message='This hospital already has a package for this treatment.'), models.CheckConstraint(condition=models.Q(('price_max_inr__isnull', True), ('price_max_inr__gte', models.F('price_min_inr')), _connector='OR'), name='pricing_package_max_at_least_min', violation_error_message='The upper price cannot be lower than the starting price.')],
            },
        ),
    ]
