# Generated by Django 6.1.1 on 2026-10-05 12:24

import apps.content.models
import apps.core.validators
import django.core.validators
import django.db.models.deletion
import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('providers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('name', models.CharField(max_length=150, verbose_name='name')),
                ('slug', models.SlugField(help_text='Used in page URLs. Changing it breaks existing links.', max_length=150, unique=True, verbose_name='slug')),
                ('credentials', models.CharField(blank=True, help_text='Example: MBBS, MD (Internal Medicine).', max_length=255, verbose_name='credentials')),
                ('bio', models.TextField(blank=True, verbose_name='short bio')),
                ('photo', models.ImageField(blank=True, upload_to=apps.content.models.author_photo_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp']), apps.core.validators.validate_image_size], verbose_name='photo')),
                ('is_medical_professional', models.BooleanField(default=False, help_text='Only medical professionals can be chosen as medical reviewers.', verbose_name='registered medical professional')),
                ('medical_registration_number', models.CharField(blank=True, help_text='NMC or state medical council registration. Internal only.', max_length=50, verbose_name='medical registration number')),
            ],
            options={
                'verbose_name': 'author',
                'verbose_name_plural': 'authors',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('is_published', models.BooleanField(default=False, verbose_name='published')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('slug', models.SlugField(help_text='Used in page URLs. Changing it breaks existing links.', max_length=200, unique=True, verbose_name='slug')),
                ('summary', models.CharField(help_text='One or two plain sentences. Shown on listing cards and used as the default search-engine description.', max_length=300, verbose_name='summary')),
                ('body', models.TextField(verbose_name='body')),
                ('cover_image', models.ImageField(blank=True, upload_to=apps.content.models.article_image_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp']), apps.core.validators.validate_image_size], verbose_name='cover image')),
                ('reviewed_on', models.DateField(blank=True, help_text='Update this every time the content is re-reviewed.', null=True, verbose_name='medically reviewed on')),
                ('published_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='first published at')),
                ('conditions', models.ManyToManyField(blank=True, related_name='articles', to='catalog.condition', verbose_name='related conditions')),
                ('treatments', models.ManyToManyField(blank=True, related_name='articles', to='catalog.treatment', verbose_name='related treatments')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='articles', to='content.author', verbose_name='author')),
                ('medical_reviewer', models.ForeignKey(blank=True, limit_choices_to={'is_medical_professional': True}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_articles', to='content.author', verbose_name='medical reviewer')),
            ],
            options={
                'verbose_name': 'article',
                'verbose_name_plural': 'articles',
                'ordering': ['-published_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('is_published', False), models.Q(('medical_reviewer__isnull', False), ('reviewed_on__isnull', False)), _connector='OR'), name='content_article_reviewed_before_publishing', violation_error_message='Add a medical reviewer and review date before publishing.')],
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('is_published', models.BooleanField(default=False, verbose_name='published')),
                ('question', models.CharField(max_length=255, verbose_name='question')),
                ('answer', models.TextField(verbose_name='answer')),
                ('display_order', models.PositiveSmallIntegerField(default=0, help_text='Lower numbers appear first.', verbose_name='display order')),
                ('condition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='catalog.condition', verbose_name='condition')),
                ('treatment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='catalog.treatment', verbose_name='treatment')),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'ordering': ['display_order', 'pk'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('condition__isnull', True), ('treatment__isnull', False)), models.Q(('condition__isnull', False), ('treatment__isnull', True)), _connector='OR'), name='content_faq_exactly_one_page', violation_error_message='Choose either a treatment or a condition (not both).')],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('is_published', models.BooleanField(default=False, verbose_name='published')),
                ('patient_display_name', models.CharField(help_text='Use what the patient agreed to, e.g. "Rahim U." or initials.', max_length=100, verbose_name='patient name as shown')),
                ('country', django_countries.fields.CountryField(max_length=2, verbose_name="patient's country")),
                ('quote', models.TextField(max_length=1500, verbose_name='testimonial')),
                ('video_url', models.URLField(blank=True, help_text='YouTube link, if the patient recorded a video.', verbose_name='video link')),
                ('treated_on', models.DateField(blank=True, null=True, verbose_name='treated on')),
                ('consent_obtained_on', models.DateField(blank=True, help_text='Date the patient agreed in writing to publish this.', null=True, verbose_name='consent obtained on')),
                ('consent_reference', models.CharField(blank=True, help_text='Internal only. Example: signed form in the case file of enquiry 1042.', max_length=255, verbose_name='where the consent is filed')),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='testimonials', to='providers.doctor', verbose_name='doctor')),
                ('hospital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='testimonials', to='providers.hospital', verbose_name='hospital')),
                ('treatment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='testimonials', to='catalog.treatment', verbose_name='treatment')),
            ],
            options={
                'verbose_name': 'testimonial',
                'verbose_name_plural': 'testimonials',
                'ordering': ['-treated_on', '-created_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('is_published', False), ('consent_obtained_on__isnull', False), _connector='OR'), name='content_testimonial_consent_before_publishing', violation_error_message="Record the patient's consent before publishing.")],
            },
        ),
    ]
