# Generated by Django 6.1.1 on 2026-10-05 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlugRedirect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('object_id', models.PositiveBigIntegerField(verbose_name='page id')),
                ('old_slug', models.SlugField(max_length=200, verbose_name='old slug')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='page type')),
            ],
            options={
                'verbose_name': 'slug redirect',
                'verbose_name_plural': 'slug redirects',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('content_type', 'old_slug'), name='core_slugredirect_unique_old_slug')],
            },
        ),
    ]
