# Generated by Django 6.1.1 on 2026-10-05 14:13

import apps.core.storage
import apps.leads.models
import django.db.models.deletion
import django_countries.fields
import phonenumber_field.modelfields
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('providers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('reference', models.CharField(default=apps.leads.models.generate_reference, editable=False, max_length=11, unique=True, verbose_name='reference')),
                ('full_name', models.CharField(max_length=150, verbose_name='full name')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='phone')),
                ('prefers_whatsapp', models.BooleanField(default=True, verbose_name='prefers WhatsApp')),
                ('country', django_countries.fields.CountryField(max_length=2, verbose_name='country')),
                ('patient_age', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name="patient's age")),
                ('message', models.TextField(max_length=5000, verbose_name='medical details and questions')),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('quote_sent', 'Quote sent'), ('travel_confirmed', 'Travel confirmed'), ('treated', 'Treated'), ('lost', 'Lost')], db_index=True, default='new', max_length=20, verbose_name='status')),
                ('internal_notes', models.TextField(blank=True, verbose_name='internal notes')),
                ('landing_page', models.CharField(blank=True, max_length=500, verbose_name='landing page')),
                ('referrer', models.CharField(blank=True, max_length=500, verbose_name='referrer')),
                ('utm_source', models.CharField(blank=True, max_length=200, verbose_name='UTM source')),
                ('utm_medium', models.CharField(blank=True, max_length=200, verbose_name='UTM medium')),
                ('utm_campaign', models.CharField(blank=True, max_length=200, verbose_name='UTM campaign')),
                ('utm_term', models.CharField(blank=True, max_length=200, verbose_name='UTM term')),
                ('utm_content', models.CharField(blank=True, max_length=200, verbose_name='UTM content')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_enquiries', to=settings.AUTH_USER_MODEL, verbose_name='case manager')),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enquiries', to='providers.doctor', verbose_name='doctor')),
                ('hospital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enquiries', to='providers.hospital', verbose_name='hospital')),
                ('treatment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enquiries', to='catalog.treatment', verbose_name='treatment')),
            ],
            options={
                'verbose_name': 'enquiry',
                'verbose_name_plural': 'enquiries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EnquiryDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(storage=apps.core.storage.private_storage, upload_to=apps.leads.models.enquiry_document_path, verbose_name='file')),
                ('original_name', models.CharField(max_length=255, verbose_name='original file name')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='uploaded at')),
                ('enquiry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='leads.enquiry', verbose_name='enquiry')),
            ],
            options={
                'verbose_name': 'medical document',
                'verbose_name_plural': 'medical documents',
                'ordering': ['uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalEnquiry',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='created at')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='updated at')),
                ('reference', models.CharField(db_index=True, default=apps.leads.models.generate_reference, editable=False, max_length=11, verbose_name='reference')),
                ('full_name', models.CharField(max_length=150, verbose_name='full name')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='phone')),
                ('prefers_whatsapp', models.BooleanField(default=True, verbose_name='prefers WhatsApp')),
                ('country', django_countries.fields.CountryField(max_length=2, verbose_name='country')),
                ('patient_age', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name="patient's age")),
                ('message', models.TextField(max_length=5000, verbose_name='medical details and questions')),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('quote_sent', 'Quote sent'), ('travel_confirmed', 'Travel confirmed'), ('treated', 'Treated'), ('lost', 'Lost')], db_index=True, default='new', max_length=20, verbose_name='status')),
                ('internal_notes', models.TextField(blank=True, verbose_name='internal notes')),
                ('landing_page', models.CharField(blank=True, max_length=500, verbose_name='landing page')),
                ('referrer', models.CharField(blank=True, max_length=500, verbose_name='referrer')),
                ('utm_source', models.CharField(blank=True, max_length=200, verbose_name='UTM source')),
                ('utm_medium', models.CharField(blank=True, max_length=200, verbose_name='UTM medium')),
                ('utm_campaign', models.CharField(blank=True, max_length=200, verbose_name='UTM campaign')),
                ('utm_term', models.CharField(blank=True, max_length=200, verbose_name='UTM term')),
                ('utm_content', models.CharField(blank=True, max_length=200, verbose_name='UTM content')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('assigned_to', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='case manager')),
                ('doctor', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='providers.doctor', verbose_name='doctor')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('hospital', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='providers.hospital', verbose_name='hospital')),
                ('treatment', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='catalog.treatment', verbose_name='treatment')),
            ],
            options={
                'verbose_name': 'historical enquiry',
                'verbose_name_plural': 'historical enquiries',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='ConsentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(choices=[('process_enquiry', 'Process my enquiry'), ('marketing', 'Marketing updates')], max_length=30, verbose_name='purpose')),
                ('consent_text_version', models.CharField(max_length=30, verbose_name='consent text version')),
                ('consent_text', models.TextField(verbose_name='consent text shown')),
                ('granted_at', models.DateTimeField(auto_now_add=True, verbose_name='granted at')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP address')),
                ('user_agent', models.CharField(blank=True, max_length=300, verbose_name='browser')),
                ('withdrawn_at', models.DateTimeField(blank=True, null=True, verbose_name='withdrawn at')),
                ('enquiry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consents', to='leads.enquiry', verbose_name='enquiry')),
            ],
            options={
                'verbose_name': 'consent record',
                'verbose_name_plural': 'consent records',
                'ordering': ['granted_at'],
                'indexes': [models.Index(fields=['ip_address', 'granted_at'], name='leads_conse_ip_addr_eb34e1_idx')],
                'constraints': [models.UniqueConstraint(fields=('enquiry', 'purpose'), name='leads_consent_one_per_purpose')],
            },
        ),
    ]
