# Generated by Django 6.1.1 on 2026-10-05 04:57

import django.db.models.functions.text
import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SourceCountry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('is_published', models.BooleanField(default=False, verbose_name='published')),
                ('country', django_countries.fields.CountryField(max_length=2, unique=True, verbose_name='country')),
                ('slug', models.SlugField(blank=True, help_text='Leave blank to generate it from the country name.', max_length=100, unique=True, verbose_name='slug')),
                ('intro', models.TextField(blank=True, verbose_name='introduction')),
                ('visa_info', models.TextField(blank=True, verbose_name='visa information')),
            ],
            options={
                'verbose_name': 'source country',
                'verbose_name_plural': 'source countries',
                'ordering': ['country'],
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('is_published', models.BooleanField(default=False, verbose_name='published')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('slug', models.SlugField(help_text='Used in page URLs. Changing it breaks existing links.', max_length=100, unique=True, verbose_name='slug')),
                ('state', models.CharField(max_length=100, verbose_name='state / union territory')),
            ],
            options={
                'verbose_name': 'city',
                'verbose_name_plural': 'cities',
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('name'), django.db.models.functions.text.Lower('state'), name='locations_city_unique_name_state', violation_error_message='This city already exists in this state.')],
            },
        ),
    ]
