# Generated by Django 6.1.1 on 2026-10-05 09:50

import apps.core.validators
import apps.providers.models
import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.core.validators
import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('locations', '0002_alter_city_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accreditation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('abbreviation', models.CharField(max_length=20, unique=True, verbose_name='abbreviation')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='full name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
            ],
            options={
                'verbose_name': 'accreditation',
                'verbose_name_plural': 'accreditations',
                'ordering': ['abbreviation'],
            },
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('is_published', models.BooleanField(default=False, verbose_name='published')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('slug', models.SlugField(help_text='Used in page URLs. Changing it breaks existing links.', max_length=200, unique=True, verbose_name='slug')),
                ('also_known_as', models.CharField(blank=True, help_text='Other names and abbreviations patients search for, comma separated. Example: TKR, knee arthroplasty.', max_length=255, verbose_name='also known as')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='street address')),
                ('postal_code', models.CharField(blank=True, max_length=6, validators=[django.core.validators.RegexValidator(message='Enter a valid 6-digit PIN code.', regex='^[1-9][0-9]{5}$')], verbose_name='PIN code')),
                ('summary', models.CharField(blank=True, help_text='One or two plain sentences. Shown on listing cards and used as the default search-engine description.', max_length=300, verbose_name='summary')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('established_year', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1800), django.core.validators.MaxValueValidator(apps.core.validators.current_year)], verbose_name='year established')),
                ('bed_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='number of beds')),
                ('image', models.ImageField(blank=True, help_text='JPG, PNG or WebP, up to 5 MB. Landscape works best.', upload_to=apps.providers.models.hospital_image_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp']), apps.core.validators.validate_image_size], verbose_name='main image')),
                ('search_vector', models.GeneratedField(db_persist=True, expression=django.contrib.postgres.search.CombinedSearchVector(django.contrib.postgres.search.CombinedSearchVector(django.contrib.postgres.search.SearchVector('name', config='english', weight='A'), '||', django.contrib.postgres.search.SearchVector('also_known_as', config='english', weight='A'), django.contrib.postgres.search.SearchConfig('english')), '||', django.contrib.postgres.search.SearchVector('summary', config='english', weight='B'), django.contrib.postgres.search.SearchConfig('english')), output_field=django.contrib.postgres.search.SearchVectorField())),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hospitals', to='locations.city', verbose_name='city')),
                ('specialities', models.ManyToManyField(blank=True, related_name='hospitals', to='catalog.speciality', verbose_name='specialities')),
            ],
            options={
                'verbose_name': 'hospital',
                'verbose_name_plural': 'hospitals',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='HospitalAccreditation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_number', models.CharField(blank=True, max_length=100, verbose_name='certificate number')),
                ('valid_until', models.DateField(blank=True, help_text='Leave blank only if the accreditation does not expire.', null=True, verbose_name='valid until')),
                ('accreditation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hospital_records', to='providers.accreditation', verbose_name='accreditation')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accreditation_records', to='providers.hospital', verbose_name='hospital')),
            ],
            options={
                'verbose_name': 'hospital accreditation',
                'verbose_name_plural': 'hospital accreditations',
            },
        ),
        migrations.AddField(
            model_name='hospital',
            name='accreditations',
            field=models.ManyToManyField(blank=True, related_name='hospitals', through='providers.HospitalAccreditation', to='providers.accreditation', verbose_name='accreditations'),
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('is_published', models.BooleanField(default=False, verbose_name='published')),
                ('name', models.CharField(help_text='Without the "Dr." prefix. The site adds it.', max_length=150, verbose_name='name')),
                ('slug', models.SlugField(help_text='Used in page URLs. Changing it breaks existing links.', max_length=150, unique=True, verbose_name='slug')),
                ('designation', models.CharField(blank=True, help_text='Example: Chairman, Institute of Orthopaedics.', max_length=200, verbose_name='designation')),
                ('qualifications', models.CharField(blank=True, help_text='Example: MBBS, MS (Orthopaedics), FRCS.', max_length=255, verbose_name='qualifications')),
                ('practising_since', models.PositiveSmallIntegerField(blank=True, help_text='Year the doctor started practising. Experience is calculated from this, so it never goes out of date.', null=True, validators=[django.core.validators.MinValueValidator(1950), django.core.validators.MaxValueValidator(apps.core.validators.current_year)], verbose_name='practising since (year)')),
                ('medical_registration_number', models.CharField(blank=True, help_text='NMC or state medical council registration. Internal only.', max_length=50, verbose_name='medical registration number')),
                ('summary', models.CharField(blank=True, help_text='One or two plain sentences. Shown on listing cards and used as the default search-engine description.', max_length=300, verbose_name='summary')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('photo', models.ImageField(blank=True, help_text='JPG, PNG or WebP, up to 5 MB. Square works best.', upload_to=apps.providers.models.doctor_photo_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp']), apps.core.validators.validate_image_size], verbose_name='photo')),
                ('search_vector', models.GeneratedField(db_persist=True, expression=django.contrib.postgres.search.CombinedSearchVector(django.contrib.postgres.search.CombinedSearchVector(django.contrib.postgres.search.SearchVector('name', config='english', weight='A'), '||', django.contrib.postgres.search.SearchVector('designation', config='english', weight='B'), django.contrib.postgres.search.SearchConfig('english')), '||', django.contrib.postgres.search.SearchVector('summary', config='english', weight='B'), django.contrib.postgres.search.SearchConfig('english')), output_field=django.contrib.postgres.search.SearchVectorField())),
                ('specialities', models.ManyToManyField(blank=True, related_name='doctors', to='catalog.speciality', verbose_name='specialities')),
                ('hospitals', models.ManyToManyField(blank=True, related_name='doctors', to='providers.hospital', verbose_name='hospitals')),
            ],
            options={
                'verbose_name': 'doctor',
                'verbose_name_plural': 'doctors',
                'ordering': ['name'],
                'indexes': [django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='providers_doctor_search_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='hospitalaccreditation',
            constraint=models.UniqueConstraint(fields=('hospital', 'accreditation'), name='providers_hospitalaccreditation_unique', violation_error_message='This hospital already has this accreditation.'),
        ),
        migrations.AddIndex(
            model_name='hospital',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='providers_hospital_search_idx'),
        ),
        migrations.AddConstraint(
            model_name='hospital',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), models.F('city'), name='providers_hospital_unique_name_per_city', violation_error_message='A hospital with this name already exists in this city.'),
        ),
    ]
