# Generated by Django 6.1.1 on 2026-10-06 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_speciality_icon'),
        ('providers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='registration_verified_on',
            field=models.DateField(blank=True, help_text='Date the team checked the number on the NMC or state medical council register. The site shows "Registration verified" only when this is set.', null=True, verbose_name='registration verified on'),
        ),
        migrations.AddConstraint(
            model_name='doctor',
            constraint=models.CheckConstraint(condition=models.Q(('registration_verified_on__isnull', True), models.Q(('medical_registration_number', ''), _negated=True), _connector='OR'), name='providers_doctor_verified_registration_has_number', violation_error_message='Enter the registration number before marking it verified.'),
        ),
    ]
