# Generated by Django 6.1.1 on 2026-10-05 07:52

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Speciality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('is_published', models.BooleanField(default=False, verbose_name='published')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('slug', models.SlugField(help_text='Used in page URLs. Changing it breaks existing links.', max_length=100, unique=True, verbose_name='slug')),
                ('summary', models.CharField(blank=True, help_text='One or two plain sentences. Shown on listing cards and used as the default search-engine description.', max_length=300, verbose_name='summary')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('display_order', models.PositiveSmallIntegerField(default=0, help_text='Lower numbers appear first.', verbose_name='display order')),
            ],
            options={
                'verbose_name': 'speciality',
                'verbose_name_plural': 'specialities',
                'ordering': ['display_order', 'name'],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='catalog_speciality_unique_name', violation_error_message='A speciality with this name already exists.')],
            },
        ),
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('is_published', models.BooleanField(default=False, verbose_name='published')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('slug', models.SlugField(help_text='Used in page URLs. Changing it breaks existing links.', max_length=200, unique=True, verbose_name='slug')),
                ('also_known_as', models.CharField(blank=True, help_text='Other names and abbreviations patients search for, comma separated. Example: TKR, knee arthroplasty.', max_length=255, verbose_name='also known as')),
                ('summary', models.CharField(blank=True, help_text='One or two plain sentences. Shown on listing cards and used as the default search-engine description.', max_length=300, verbose_name='summary')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('hospital_stay_days', models.PositiveSmallIntegerField(blank=True, help_text='Typical number of days admitted in hospital.', null=True, verbose_name='hospital stay (days)')),
                ('stay_in_india_days', models.PositiveSmallIntegerField(blank=True, help_text='Typical total stay, including recovery before flying home.', null=True, verbose_name='total stay in India (days)')),
                ('search_vector', models.GeneratedField(db_persist=True, expression=django.contrib.postgres.search.CombinedSearchVector(django.contrib.postgres.search.CombinedSearchVector(django.contrib.postgres.search.SearchVector('name', config='english', weight='A'), '||', django.contrib.postgres.search.SearchVector('also_known_as', config='english', weight='A'), django.contrib.postgres.search.SearchConfig('english')), '||', django.contrib.postgres.search.SearchVector('summary', config='english', weight='B'), django.contrib.postgres.search.SearchConfig('english')), output_field=django.contrib.postgres.search.SearchVectorField())),
                ('speciality', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='treatments', to='catalog.speciality', verbose_name='speciality')),
            ],
            options={
                'verbose_name': 'treatment',
                'verbose_name_plural': 'treatments',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('is_published', models.BooleanField(default=False, verbose_name='published')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('slug', models.SlugField(help_text='Used in page URLs. Changing it breaks existing links.', max_length=200, unique=True, verbose_name='slug')),
                ('also_known_as', models.CharField(blank=True, help_text='Other names and abbreviations patients search for, comma separated. Example: TKR, knee arthroplasty.', max_length=255, verbose_name='also known as')),
                ('summary', models.CharField(blank=True, help_text='One or two plain sentences. Shown on listing cards and used as the default search-engine description.', max_length=300, verbose_name='summary')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('search_vector', models.GeneratedField(db_persist=True, expression=django.contrib.postgres.search.CombinedSearchVector(django.contrib.postgres.search.CombinedSearchVector(django.contrib.postgres.search.SearchVector('name', config='english', weight='A'), '||', django.contrib.postgres.search.SearchVector('also_known_as', config='english', weight='A'), django.contrib.postgres.search.SearchConfig('english')), '||', django.contrib.postgres.search.SearchVector('summary', config='english', weight='B'), django.contrib.postgres.search.SearchConfig('english')), output_field=django.contrib.postgres.search.SearchVectorField())),
                ('treatments', models.ManyToManyField(blank=True, help_text='Treatments that address this condition.', related_name='conditions', to='catalog.treatment', verbose_name='treatments')),
            ],
            options={
                'verbose_name': 'condition',
                'verbose_name_plural': 'conditions',
                'ordering': ['name'],
            },
        ),
        migrations.AddIndex(
            model_name='treatment',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='catalog_treatment_search_idx'),
        ),
        migrations.AddConstraint(
            model_name='treatment',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='catalog_treatment_unique_name', violation_error_message='A treatment with this name already exists.'),
        ),
        migrations.AddConstraint(
            model_name='treatment',
            constraint=models.CheckConstraint(condition=models.Q(('hospital_stay_days__isnull', True), ('stay_in_india_days__isnull', True), ('stay_in_india_days__gte', models.F('hospital_stay_days')), _connector='OR'), name='catalog_treatment_stay_covers_hospital_stay', violation_error_message='Total stay in India cannot be shorter than the hospital stay.'),
        ),
        migrations.AddIndex(
            model_name='condition',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='catalog_condition_search_idx'),
        ),
        migrations.AddConstraint(
            model_name='condition',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='catalog_condition_unique_name', violation_error_message='A condition with this name already exists.'),
        ),
    ]
