# Generated by Django 6.1.1 on 2026-10-06 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='speciality',
            name='icon',
            field=models.CharField(choices=[('stethoscope', 'Stethoscope (general)'), ('heart-pulse', 'Heart (cardiology)'), ('bone', 'Bone (orthopaedics)'), ('ribbon', 'Ribbon (oncology)'), ('brain', 'Brain (neurology, neurosurgery)'), ('baby', 'Baby (fertility, paediatrics)'), ('eye', 'Eye (ophthalmology)'), ('ear', 'Ear (ENT)'), ('smile', 'Smile (dental)'), ('activity', 'Pulse (other)')], default='stethoscope', max_length=20, verbose_name='icon'),
        ),
    ]
